### ISSUE TITLE
Feature-request: Cannot create bookmark?

### ISSUE THREAD

**Issue by haadr** [ueokande/vim-vixen#165]
I don't think it's currently possible to create/add bookmarks. The default Ctrl+D key is overriden by vim vixen. I cannot find a mention of bookmarks in the readme.

**Comment by jalcine** [comment]
Yeah, same. As far as it seems to be; bookmark creation support doesn't work and is disabled by this plugin. Making emulating the ":markadd" in Vim would help?

**Comment by DwordPtr** [comment]
I would like some keyboard shortcut to bookmark pages while using vim-vixen although I don't know enough about the code to fix this.

**Comment by owenstranathan** [comment]
This just works for me if I use ctrl+shift+d

**Comment by owenstranathan** [comment]
My work around for this is to edit the key mapping json object. You can get to it through firefox's add ons page put `about:addons` in your search bar.  
Then click into vim vixen's options and find the `<C-D>` key, then change this to `<C-S-D>` so that scroll by half a page is now mapped to ctrl+shift+d and ctrl+d is no longer shadowed and results in the default firefox new bookmark behavior.

**Comment by DwordPtr** [comment]
it actually works for my by default but I didn't see the binding on any of the cheat sheets.

Thanks everyone.

**Comment by gmarmstrong** [comment]
In the mean time, you can do:
* <kbd>Shift</kbd>+<kbd>Esc</kbd> to disable Vixen
* <kbd>Ctrl</kbd>+<kbd>d</kbd> to bookmark the page
* <kbd>Shift</kbd>+<kbd>Esc</kbd> to enable Vixen
