### ISSUE TITLE
implement :q to close tab

### ISSUE THREAD

**Issue by robehickman** [ueokande/vim-vixen#260]
### I'm opening this issue because:

- [ ] I'll report a bug
- [* ] I'll propose a new feature

Vimperator has always allowed the current tab to be closed with ':q' command, it would be good if this addon also supported that. Also would be good to allow the mapping of ':' commands through the JSON options.

**Comment by mvhulten** [comment]
I also think this would be a good feature.  Furthermore, `:qa` can be used to close the web browser, or maybe all tabs on the current window.

I add yet another proposal here, because the right choice should be made in this context.  It concerns the `d` mapping to closing the current tab.  I now accidentally close tabs, so I'd be happier when this mapping is removed.  Furthermore, it does not feel very intuitive: removing (as `d` is used in vi) is not the same as closing.  Finally, Ctrl-W/Q works fine, so there is not really a need for a binding to closing tabs or windows.  Nonetheless, `:q` and `:qa` can be nice additions that should not result in usage problems as I am having with `d`.

**Comment by ueokande** [comment]
resolved
