### ISSUE TITLE
J/K to change tab not work on firefox 67,win 7/10

### ISSUE THREAD

**Issue by DamonDBT** [ueokande/vim-vixen#607]
### I'm opening this issue because:

- [x] I'll report a bug 

### Description
J/K to change tab not work on firefox 67,win 7/10
  

#### System configuration

- Operating system: win7 and win10
- Firefox version: 67
- Vim-Vixen version: 0.23

#### Console logs

Any relevant log in developer tools:

**Comment by AlexeySachkov** [comment]
Hi @DamonDBT,

I've just checked, this functionality works for me on Firefox 67.0.2 (32-bit) on Windows 10.

Is there anything else from vim-vixen that doesn't work on your side? Like scrolling with `j`/`k`, opening console with `t`/`o`?

**Comment by DamonDBT** [comment]
no，Only a few uppercase functions  like J  K  G can not be used

**Comment by DamonDBT** [comment]
> 
> 
> Hi @DamonDBT,
> 
> I've just checked, this functionality works for me on Firefox 67.0.2 (32-bit) on Windows 10.
> 
> Is there anything else from vim-vixen that doesn't work on your side? Like scrolling with `j`/`k`, opening console with `t`/`o`?
no，Only a few uppercase functions like J K G can not be used

**Comment by chillycuz** [comment]
Just to add some possibly related information, I think my issue may be related since I originally diagnosed it as the original poster did. I am using Firefox 67.0.2 (64-bit) on Arch LInux. Since the update to 67 (I think), I have been experiencing frequent tab crashes. After restoring the tabs, Vim Vixen no longer works. Other extensions appear to continue working. After a restart, everything works fine again...until a tab crash. I have tried clearing all caches, but have had no success.
p.s. Love the extension. :)

**Comment by chillycuz** [comment]
Sorry. Just read OP's description a little closer. Our issues may be related, but they are different. Should have created a new issue.

**Comment by MartinRenze** [comment]
Same issue here: Ubuntu x64 - Firefox 68.0.1

scrolling with j k is working and gt gT is also working

**Comment by DamonDBT** [comment]
i find the a way ,
press shift+j  ==J
pres  shift+k ==K
